apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: service-b
  namespace: k8s-example2
  labels:
    app: service-b
spec:
  serviceName: service-b
  selector:
    matchLabels:
      app: service-b
  replicas: 3
  template:
    metadata:
      labels:
        app: service-b
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: service-b
        image: fananchong/k8s-example2
        command: [ "/service_b" ]

---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: k8s-example2
  labels:
    app: service-b
spec:
  ports:
    - port: 3456
  clusterIP: None
  selector:
    app: service-b
