apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: k8s-example2
  labels:
    app: service-a
spec:
  selector:
    matchLabels:
      app: service-a
  replicas: 3
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: fananchong/k8s-example2
        command: [ "/service_a2" ]
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: k8s-example2
  labels:
    app: service-a
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30080
  selector:
    app: service-a
