apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: service-a
  name: service-a
  namespace: k8s-example2

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: service-a
  namespace: k8s-example2
  labels:
    app: service-a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: service-a
    namespace: k8s-example2

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: k8s-example2
  labels:
    app: service-a
spec:
  selector:
    matchLabels:
      app: service-a
  replicas: 3
  template:
    metadata:
      labels:
        app: service-a
    spec:
      serviceAccountName: service-a
      containers:
      - name: service-a
        image: fananchong/k8s-example2
        command: [ "/service_a" ]
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: k8s-example2
  labels:
    app: service-a
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30080
  selector:
    app: service-a

