apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-redis-pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pv-redis-1
