apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-redis-pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pv-redis-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-redis-pv-2
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pv-redis-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-redis-pv-3
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pv-redis-3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-redis-pv-4
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pv-redis-4
