apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: sa
  name: sa
  namespace: k8s-example2

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: sa
  namespace: k8s-example2
  labels:
    app: sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: sa
    namespace: k8s-example2
