apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: k8s-example3
  labels:
    app: service-a
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30083
  selector:
    app: service-a

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: k8s-example3
  labels:
    app: service-a
spec:
  selector:
    matchLabels:
      app: service-a
  replicas: 3
  template:
    metadata:
      labels:
        app: service-a
    spec:
      serviceAccountName: sa
      containers:
      - name: service-a
        image: fananchong/k8s-example3
        imagePullPolicy: Always
        command: [ "/service_a" ]
        ports:
        - containerPort: 8000


